// Java Program for Kadane's Algorithm.



 /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setLayout(null);
        add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setText("Good Morning, Rohit");
        add(jLabel3);
        jLabel3.setBounds(520, 30, 180, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\cartoon-businessman-in-suit-portrait-in-circle-vector-17571127.jpg")); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(780, 20, 70, 80);

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel5.setText("Choose your style");
        add(jLabel5);
        jLabel5.setBounds(520, 160, 130, 20);

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel6.setText("See all");
        add(jLabel6);
        jLabel6.setBounds(790, 160, 50, 14);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\77588283-espresso-coffee-different-types-of-coffee-single-icon-in-cartoon-style-rater-bitmap-symbol-stock-ill.jpg")); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(520, 190, 130, 120);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\ristretto-glass-different-types-coffee-single-icon-cartoon-style-vector-symbol-stock-illustration-web-90353945.jpg")); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(720, 190, 130, 120);

        jButton1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\grwe1.jpg")); // NOI18N
        add(jButton1);
        jButton1.setBounds(720, 350, 130, 30);

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel9.setText("Collect your Discount!");
        add(jLabel9);
        jLabel9.setBounds(520, 400, 150, 18);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\coffee.jpg")); // NOI18N
        add(jLabel10);
        jLabel10.setBounds(520, 430, 340, 170);

        jButton3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton3.setText("Home ");
        add(jButton3);
        jButton3.setBounds(520, 600, 80, 30);

        jButton4.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton4.setText("Orders");
        add(jButton4);
        jButton4.setBounds(600, 600, 90, 30);

        jButton5.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton5.setText("Favorite");
        add(jButton5);
        jButton5.setBounds(690, 600, 90, 30);

        jButton6.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton6.setText("Profile");
        add(jButton6);
        jButton6.setBounds(780, 600, 80, 30);

        jLabel12.setText(" Let's select the best taste of your");
        add(jLabel12);
        jLabel12.setBounds(520, 70, 200, 20);

        jLabel13.setText(" next coffee break");
        add(jLabel13);
        jLabel13.setBounds(520, 90, 150, 14);

        jButton7.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\grwe1.jpg")); // NOI18N
        add(jButton7);
        jButton7.setBounds(520, 350, 130, 30);

        jLabel14.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel14.setText("$ 3.99");
        add(jLabel14);
        jLabel14.setBounds(530, 320, 70, 18);

        jLabel15.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel15.setText("$ 4.99");
        add(jLabel15);
        jLabel15.setBounds(720, 320, 40, 14);

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\Solid-Light-Brown-Background.jpg")); // NOI18N
        add(jLabel18);
        jLabel18.setBounds(510, 10, 350, 140);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\plain-white-background.jpg")); // NOI18N
        add(jLabel16);
        jLabel16.setBounds(510, 10, 350, 620);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\New Acer\\Desktop\\rohit\\pexels-toni-cuenca-585750.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(4, 0, 1230, 690);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
